MVC_Project_EmployeeDatabase/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVC_Project.Models
{
    [Table("tblDepartment")]
    public class Department
    {
        public int ID { get; set; }
        public String Name { get; set; }
        public List<Employee> Employees { get; set; }
    }
}

MVC_Project_EmployeeDatabase/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVC_Project.Models
{
    /// <summary>
    /// Below is an example of serialization. Table maps data from MS Server in table tblEmployee to Employee.
    /// When a new instance of Employee is created, Table's methods will be used to help get/set the values below. 
    /// </summary>
    [Table("tblEmployee")]
    public class Employee
    {
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }
        public int DepartmentId {get;set;}
    }
}

MVC_Project_EmployeeDatabase/Models/EmployeeContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

/// <comment>
/// EmployeeContext: EmployeeContext creates a link between a MS server and the program. EmployeeContext class will be used to access the server and then employee class will be used to select the table information to get/set. 
/// </comment>
/// <remark>
/// Check Web.Config.  There the EmployeeContext is defined and a connection between the Ms Server and the EmployeeContext Data is linked. 
/// </remark>

namespace MVC_Project.Models
{
    public class EmployeeContext : DbContext
    {
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Department> Departments { get; set; }
    }
}

MVC_Project_EmployeeDatabase/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Project.Models;

///<summary>
///     DepartmentsController controls how data is used/got.  
///     
///     EmployeeContext references the server.
///     Employee acts like a table. We will grab data from the Server and map it to the Employee data set.
///     
///     ActionResult Index is used in Views index department page. It is passed data selected by the user and 
///     a list of tables is returned.
///     
///</summary>
namespace MVC_Project.Controllers
{
    public class DepartmentsController : Controller
    {

        public ActionResult Index()
        {
            EmployeeContext employeeContext = new EmployeeContext();
            List<Department> departments = employeeContext.Departments.ToList();
            return View(departments);
        }

    }
}

MVC_Project_EmployeeDatabase/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Project.Models;

/// <comment>
/// Summary:
///     EmployeeController controls how data is used/got.  
///     
///     EmployeeContext references the server.
///     Employee acts like a table. We will grab data from the Server and map it to the Employee data set.
///     
///     ActionResult Index and Details are used in Views index and detail pages. They are passed in data selected by the user and 
///     a list of tables is returned.
///     
/// </comment>

namespace MVC_Project.Controllers
{
    public class EmployeeController : Controller
    {
        public ActionResult Index(int departmentId)
        {
            EmployeeContext employeeContext = new EmployeeContext();
            List<Employee> employees = employeeContext.Employees.Where(emp => emp.DepartmentId == departmentId).ToList();
            return View(employees);
        }
        public ActionResult Details(int id)
        {
            EmployeeContext employeeContext = new EmployeeContext();
            Employee employee = employeeContext.Employees.Single(emp => emp.EmployeeID == id);
            return View(employee);
        }


    }
}

MVC_Project_EmployeeDatabase/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Project.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            /// Empty Page.  
            return View();
        }

    }
}

MVC_Project_EmployeeDatabase/Views/Departments/Index.cshtml
@using MVC_Project.Models;

@model IEnumerable<Department>
<!-- IEnumerable is used to make model represent a list. Otherwise, the foreach used below would not work. -->

@{
    ViewBag.Title = "Department List";
}
<div style="font-family:Arial">
<h2>Department List</h2>
    <ul>
        @foreach (Department department in @Model)
        {
        <li>
            @Html.ActionLink(department.Name, "Index", "Employee", new {departmentId = department.ID},null)
        </li>
        }
    </ul>
</div> 

MVC_Project_EmployeeDatabase/Views/Employee/Details.cshtml
<!-- Model -->
@model MVC_Project.Models.Employee

@{
    ViewBag.Title = "Employee Details";
}

<h2>Employee Details</h2>
<table style="font-family:Arial">
    <tr><td>Employee ID:</td><td>@Model.EmployeeID</td></tr>
    <tr><td>Name:</td><td>@Model.Name</td></tr>
    <tr><td>Gender:</td><td>@Model.Gender</td></tr>
    <tr><td>City:</td><td>@Model.City</td></tr>
    
</table>
@Html.ActionLink("Back to Employee List", "Index", new { departmentId = @Model.DepartmentId })

MVC_Project_EmployeeDatabase/Views/Employee/Index.cshtml
@model IEnumerable<MVC_Project.Models.Employee>
<!-- IEnumerable is used to make model represent a list. Otherwise, the foreach used below would not work. -->

@using MVC_Project.Models;

@{
    ViewBag.Title = "Employee List";
}
<div style="font-family:Arial ">
<h2>Employee List</h2>
    <ul>
        @foreach(Employee employee in @Model)
        {
            <li>
                @Html.ActionLink(employee.Name, "Details", new {id = employee.EmployeeID})
            </li>
        }
    </ul>
    @Html.ActionLink("Back to Department List", "Index", "Departments")
    </div>

MVC_Project_EmployeeDatabase/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Home Page</h2>
@Html.ActionLink("Link to Departments","Index","Departments")