Simple Inventory System Version 1/Models/AccountContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace Simple_Inventory_System.Models
{
    // AccountContext will be called to retrieve data from SQL server.  Essentially, if this was an SQL query this statement would be for example "From Customers".
    // It defines what Table we are getting data from.

    public class AccountContext : DbContext
    {
        public DbSet<Customer> Customers{get; set;}
        public DbSet<Employee> Employees{get; set;}
        public DbSet<Order> Orders { get; set; }
                
    }
}

Simple Inventory System Version 1/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

/// Here we Select what data we want.  
/// Select "List of Fields" From Customers
/// Then Place in the data fields defined.

namespace Simple_Inventory_System.Models
{
    [Table("Customers")]
    public class Customer
    {
        public String CustomerID { get; set; }
        public String CompanyName { get; set; }
        public String ContactName { get; set; }
        public String ContactTitle { get; set; }
        public String Address { get; set; }
        public String City { get; set; }
        public String Region { get; set; } 
        public String PostalCode { get; set; }
        public String Country {get;set;}
        public String Phone { get; set; }

        // This will store a list of table order information.
        public virtual ICollection<Order> Orders { get; set; }
    }
}

Simple Inventory System Version 1/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Linq;
using System.Web;

/// Here we Select what data we want.  
/// Select "List of Fields" From Employees 
/// Then Place in the data fields defined.
/// 
namespace Simple_Inventory_System.Models
{
    [Table("Employees")]
    public class Employee
    {
        public int EmployeeID { get; set; }
        public String LastName { get; set; }
        public String FirstName { get; set; }
        public String Title { get; set; }
        public DateTime HireDate { get; set; } 
        public String Address { get; set; }
        public String City { get; set; }
        public String Region { get; set; }
        public String PostalCode { get; set; }
        public String Country { get; set; }
        public String HomePhone { get; set; }
        public String Extension { get; set; }
    }
}

Simple Inventory System Version 1/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

/// Here we Select what data we want.  
/// Select "List of Fields" From Orders
/// Then Place in the data fields defined.
/// 

namespace Simple_Inventory_System.Models
{
    [Table("Orders")]
    public class Order
    {
        public int OrderID { get; set; }
        public String CustomerID { get; set; }
        public int EmployeeID { get; set; }
        public DateTime OrderDate { get; set; }
        public DateTime RequiredDate { get; set; }
        public DateTime sDate;
        /// <summary>
        ///  Some Times ShippedDate will be Null.  DateTime requires a value be present so Nullabe<dateTime> is used to check 
        ///  if its a Null entry.  If its null it will assign it a temp value of "1/1/1" and used to signify black space.
        /// </summary>
        public Nullable<DateTime> ShippedDate {
            get
            {
                return sDate;
            }
            set
            {
                if (!value.HasValue)
                {
                    sDate = new DateTime(1, 1, 1);
                }
                else
                {
                    sDate = value.Value;
                }
            }
        }
        public String ShipName { get; set; }
        public String ShipAddress { get; set; }
        public String ShipCity { get; set; }
        public String ShipRegion { get; set; }
        public String ShipPostalCode { get; set; }
        public String ShipCountry { get; set; }
        
   }
}

Simple Inventory System Version 1/Controllers/CustomerController.cs
using Simple_Inventory_System.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Simple_Inventory_System.Controllers
{
    public class CustomerController : Controller
    {
        public ActionResult Index()
        {
            AccountContext accountContext = new AccountContext();
            List<Customer> customers = accountContext.Customers.ToList();
            return View(customers);
        }

        public ActionResult Details(String id)
        {
            AccountContext accountContext = new AccountContext();
            Customer customer = accountContext.Customers.Single(cust => cust.CustomerID == id);
            customer.Orders = accountContext.Orders.Where(order => order.CustomerID == id).ToList();
            return View(customer);
        }

    }
}

Simple Inventory System Version 1/Controllers/EmployeeController.cs
using Simple_Inventory_System.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Simple_Inventory_System.Controllers
{
    public class EmployeeController : Controller
    {
        public ActionResult Index()
        {
            AccountContext accountContext = new AccountContext();
            List<Employee> employees = accountContext.Employees.ToList();
            return View(employees);
        }
        public ActionResult Details(int id)
        {
            AccountContext accountContext = new AccountContext();
            Employee employee = accountContext.Employees.Single(emp => emp.EmployeeID == id);
            return View(employee);
        }

    }
}

Simple Inventory System Version 1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Simple_Inventory_System.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Simple Inventory System Version 1/Views/Customer/Details.cshtml
@using Simple_Inventory_System.Models;
@model Customer

 


@{
    ViewBag.Title = "Details";
    DateTime date = new DateTime(1,1,1);
 }

<h2>Details</h2>

<style>
    table, th, td {
        border: 1px solid black;
        font-family: Arial;
    }

    table {
        width: 75%;
    }

    td {
        text-align: center;
    }
</style>

<div>
    <h3>Customer Details</h3>
    <table>
        <tr><th>Company Name</th><th>Contact</th><th>Title</th><th>Address</th><th>City</th><th>Country</th></tr>
            <tr>
                <td>@Model.CompanyName</td>
                <td>@Model.ContactName</td>
                <td>@Model.ContactTitle</td>
                <td>@Model.Address</td>
                <td>@Model.City</td>
                <td>@Model.Country</td>
            </tr>
    </table>
    <table>
        <tr><th>OrderID</th><th>OrderDate</th><th>RequiredDate</th><th>ShippedDate</th><th>ShipName</th><th>ShipAddress</th><th>ShipCity</th><th>ShipRegion</th><th>ShipPostcode </th><th>ShipCountry</th></tr>
        <br />
        @if(Model.Orders != null)
        { 
            foreach (Order ord in Model.Orders)
            {
                <tr><td>@ord.OrderID</td><td>@ord.OrderDate.ToString("MM/dd/yyyy")</td><td>@ord.RequiredDate.ToString("MM/dd/yyyy")</td><td>@if (ord.ShippedDate == date) { }else
                    { @ord.ShippedDate.Value.ToString("MM/dd/yyyy")}</td>
        <td>@ord.ShipName</td><td>@ord.ShipAddress</td><td>@ord.ShipCity</td><td>@ord.ShipRegion</td><td>@ord.ShipPostalCode </td><td>@ord.ShipCountry</td></tr>
            }
        }
        else
        {
            <tr><td></td><td></td><td></td><th></th><td></td><td></td><td></td><td></td><td></td></tr>
        }
    </table>
    <br />
    @Html.ActionLink("Back to Customer Index", "Index", "Customer")

</div>

Simple Inventory System Version 1/Views/Customer/Index.cshtml
@model  IEnumerable<Simple_Inventory_System.Models.Customer>

@{
    ViewBag.Title = "Index";
}

<style>
    table, th, td {
        border: 1px solid black;
        font-family: Arial;
    }

    table {
        width: 75%;
    }

    td {
        text-align: center;
    }
</style>

@using Simple_Inventory_System.Models

<div>
    <h3>Customer Information</h3>
    <table>
        <tr><th>Company Name</th><th>Contact</th><th>Title</th><th>Address</th><th>City</th><th>Country</th></tr>
        @foreach (Customer customer in @Model)
        {
            <tr>
                <td>@Html.ActionLink(customer.CompanyName, "Details", new { id = customer.CustomerID })</td>
                <td>@customer.ContactName</td>
                <td>@customer.ContactTitle</td>
                <td>@customer.Address</td>
                <td>@customer.City</td>
                <td>@customer.Country</td>
            </tr>
        }
    </table>
    <br />
    @Html.ActionLink("Back to Home Page", "Index", "Home")

</div>

Simple Inventory System Version 1/Views/Employee/Details.cshtml
@using Simple_Inventory_System.Models

@model Employee

@{
    ViewBag.Title = "Details";
}

<style>
    th, td {
        border: 1px solid black;
        font-family: Arial;
    }

    table {
        width: 100%;
    }

    td {
        text-align: center;
    }
    img{
        height: 125px;
        width: 125px;
            display: block;
    margin-left: auto;
    margin-right: auto;
    }

/* For browsers that understand min-width */
        .width {
            width: 75%;
            min-width:150px;
                display: block;
    margin-left: auto;
    margin-right: auto;
        }

        /* IE6 Only */
        * html .minwidth {
            border-left: 150px solid white;
            position: relative;
            float: left;
        }

        /* IE6 Only */
        * html .wrapper {
            margin-left: -250px;
            position: relative;
            float: left;
        }

        .left {
            float: left;
            width: 75%;
        }

        .right {
            float: left;
            width:25%;

        }

</style>

<div class="width">
    <h2>Employee Details</h2>
    <div class="minwidth">
        <div class="wrapper">
            <div class="left">
                <table>
                    <tr>
                        <th>Employee ID:</th>
                        <td>@Model.EmployeeID</td>
                    </tr>
                    <tr>
                        <th>Position:</th>
                        <td>@Model.Title</td>
                    </tr>
                    <tr>
                        <th>Hire Date:</th>
                        <td>@Model.HireDate</td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <th>First Name:</th>
                        <td>@Model.FirstName</td>
                        <th>Last Name:</th>
                        <td>@Model.LastName</td>
                    </tr>
                    <tr>
                        <th>Home Phone:</th>
                        <td>@Model.HomePhone</td>
                        <th>Extension</th>
                        <td>@Model.Extension</td>
                    </tr>
                </table>            </div>
            <div class="right">
                <img src="https://drivenlocal.com/wp-content/themes/newdl/images/icon-user-default.png">
            </div>
        </div>
    </div>
    <table>
        <tr>

            <th>Address:</th>
            <td>@Model.Address</td>
            <th>City:</th>
            <td>@Model.City</td>
            <th>Country:</th>
            <td>@Model.Country</td>
            <th>Region:</th>
            <td>@Model.Region</td>
            <th>Postal Code:</th>
            <td>@Model.PostalCode</td>
        </tr>
    </table>

    <br />
    @Html.ActionLink("Back to Employee List", "Index", "Employee")
</div>



Simple Inventory System Version 1/Views/Employee/Index.cshtml


@model IEnumerable<Simple_Inventory_System.Models.Employee>
@using Simple_Inventory_System.Models;
@{
    ViewBag.Title = "Company Staff";
}

<style>
    table, th, td {
        border: 1px solid black;
        font-family:Arial;
    }
    table {width: 75%;}
    td {text-align:center;}
</style>

<div>
    <h3>Company Staff</h3>
    <table>
        <tr><th>Employee Name</th><th>Title</th><th>Phone Number</th><th>Extenstion</th></tr>
        @foreach (Employee employee in @Model)
        {
            <tr>
                <td>@Html.ActionLink(employee.FirstName +" "+ employee.LastName, "Details", new { id = employee.EmployeeID })</td>
                <td>@employee.Title</td>
                <td>@employee.HomePhone</td>
                <td>@employee.Extension</td>
            </tr>
        }
        </table>
    <br />
    @Html.ActionLink("Back to Home Page","Index","Home")

</div>

Simple Inventory System Version 1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<div>
    <ul>
        <li>@Html.ActionLink("Our Company Staff", "Index", "Employee") </li>
        <li>@Html.ActionLink("Current Customers","Index","Customer") </li>
    </ul>
</div>